-libraryjars /home/cesar/sources/WTK2.5.1/lib/midpapi10.jar:/home/cesar/sources/WTK2.5.1/lib/cldcapi10.jar:/home/cesar/sources/WTK2.5.1/lib/cldcapi10.jar
-injars /home/cesar/sources/WTK2.5.1/apps/Bubblet/bin/Bubblet.jar
-outjar /tmp/Bubblet.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
